mermaid
graph LR
    T-05 --> T-07
    T-04 --> T-09
    T-05 --> T-09
    T-07 --> T-09
    T-01 --> T-06
    T-10 --> T-14
    T-08 --> T-15
    T-17 --> T-15
    T-03 --> T-17
    T-06 --> T-17
    T-08 --> T-17
    T-16 --> T-17
    T-03 --> T-18
    T-06 --> T-18
    T-12 --> T-18
    T-14 --> T-20
    T-14 --> T-21
    T-15 --> T-21
    T-06 --> T-22
    T-06 --> T-23
    T-14 --> T-24
    T-15 --> T-24
    T-17 --> T-24
    T-20 --> T-24
    T-12 --> T-25
    T-14 --> T-27
    T-15 --> T-27
    T-20 --> T-27
    T-16 --> T-28
    T-17 --> T-28
    T-22 --> T-28
